version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  emqx:
    image: emqx/emqx:5.3.2
    ports:
      - "1883:1883"
      - "8083:8083" # WebSocket
      - "8084:8084" # WebSocket SSL
      - "18083:18083" # Dashboard
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard
    volumes:
      - emqx-data:/opt/emqx/data

  ingestor:
    build: .
    env_file: .env.example
    depends_on:
      - kafka
      - emqx
    ports:
      - "8080:8080"

volumes:
  emqx-data:
