services:
  kafka:
    image: apache/kafka:4.1.1
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - "9092:9092"
    networks:
      - anchr-net

  emqx:
    image: emqx/emqx:5.3.2
    ports:
      - "1883:1883"
      - "8083:8083" # WebSocket
      - "8084:8084" # WebSocket SSL
      - "18083:18083" # Dashboard
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard
    volumes:
      - emqx-data:/opt/emqx/data
    networks:
      - anchr-net

  ingestor:
    build: .
    env_file: .env
    depends_on:
      - kafka
      - emqx
    ports:
      - "8080:8080"
    networks:
      - anchr-net

volumes:
  emqx-data:

networks:
  anchr-net:
    name: anchr-net
    driver: bridge
