apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ingestor.fullname" . }}
  labels:
    {{- include "kafka-ingestor.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
