{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka-ingestor.fullname" . }}
  labels:
    {{- include "kafka-ingestor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kafka-ingestor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
