apiVersion: v1
kind: Secret
metadata:
  name: anchr-kafka-ingestor
  labels:
    app: anchr-kafka-ingestor
type: Opaque
stringData:
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_CA_FILE: ""
  KAFKA_SASL_MECHANISM: ""
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  KAFKA_TLS_CA_FILE: ""
  KAFKA_TLS_CERT_FILE: ""
  KAFKA_TLS_KEY_FILE: ""
  KAFKA_TLS_SKIP_VERIFY: "false"
